#! /usr/bin/env node
const path = require('path');
const ROOT_DIR = path.resolve(__dirname, '..');
const TOOLS_DIR = path.resolve(ROOT_DIR, 'tools');

const buildProto = require(path.resolve(TOOLS_DIR, `build-proto`));

const JS_OUT = path.resolve(ROOT_DIR, 'app/src/api/proto/generated');
const GO_OUT = path.resolve(ROOT_DIR, 'server/app/routes/grpcweb/service/proto');

buildProto(__dirname, GO_OUT, JS_OUT);
